### ISSUE TITLE
使用aardio 打包后 无法正常运行

### ISSUE THREAD

**Issue by redcatH** [aardio/yapi-electron#2]
错误应用程序名称: electron.dll，版本: 11.2.1.0，时间戳: 0x600b6b52
错误模块名称: electron.dll，版本: 11.2.1.0，时间戳: 0x600b6b52
异常代码: 0xc0000005
错误偏移量: 0x0273431b
错误进程 ID: 0x31ac
错误应用程序启动时间: 0x01d7440a70ccb449
错误应用程序路径: C:\Users\xxx\AppData\Local\aardio\std\electron\11.2.1\electron.dll
错误模块路径: C:\Users\xxx\AppData\Local\aardio\std\electron\11.2.1\electron.dll
报告 ID: 724239ea-48a1-4af5-bb09-fc6fba4d2a91
错误程序包全名: 
错误程序包相对应用程序 ID:

**Comment by aardio** [comment]
请更新 aardio 后再试一下应该正常了。
